/**
 * ProteinTrack Food & Bio-Nutrition Database
 * Verified laboratory telemetry matching USDA FoodData Central & DIAAS criteria
 */
const FOODS_DATA = [
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    subtext: "Boneless, skinless, cooked · 165 kcal",
    category: "poultry",
    categoryLabel: "POULTRY",
    proteinPer100g: 31.0,
    caloriesPer100g: 165,
    carbsPer100g: 0,
    fatPer100g: 3.6,
    commonServing: "1 breast ≈ 172g",
    servingWeightG: 172,
    proteinPerServe: 53.3,
    caloriesPerServe: 284,
    carbsPerServe: 0,
    fatPerServe: 6.2,
    leucinePerServe: 2.48,
    diaasScore: 1.08,
    icon: "drumstick"
  },
  {
    id: "whey-isolate",
    name: "Whey Protein Isolate",
    subtext: "Cold-filtered unflavored · 370 kcal",
    category: "supplement",
    categoryLabel: "SUPPLEMENT",
    proteinPer100g: 90.0,
    caloriesPer100g: 370,
    carbsPer100g: 1.0,
    fatPer100g: 0.8,
    commonServing: "1 scoop ≈ 30g",
    servingWeightG: 30,
    proteinPerServe: 27.0,
    caloriesPerServe: 111,
    carbsPerServe: 0.3,
    fatPerServe: 0.2,
    leucinePerServe: 3.20,
    diaasScore: 1.15,
    icon: "flask"
  },
  {
    id: "salmon-fillet",
    name: "Atlantic Salmon Fillet",
    subtext: "Wild caught, grilled · 206 kcal",
    category: "seafood",
    categoryLabel: "SEAFOOD",
    proteinPer100g: 25.4,
    caloriesPer100g: 206,
    carbsPer100g: 0,
    fatPer100g: 11.2,
    commonServing: "1 fillet ≈ 198g",
    servingWeightG: 198,
    proteinPerServe: 50.3,
    caloriesPerServe: 408,
    carbsPerServe: 0,
    fatPerServe: 22.2,
    leucinePerServe: 2.10,
    diaasScore: 1.05,
    icon: "fish"
  },
  {
    id: "greek-yogurt",
    name: "Greek Yogurt (0% Fat)",
    subtext: "Strained authentic plain · 59 kcal",
    category: "dairy",
    categoryLabel: "DAIRY",
    proteinPer100g: 10.3,
    caloriesPer100g: 59,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    commonServing: "1 container ≈ 170g",
    servingWeightG: 170,
    proteinPerServe: 17.5,
    caloriesPerServe: 100,
    carbsPerServe: 6.1,
    fatPerServe: 0.7,
    leucinePerServe: 1.15,
    diaasScore: 1.18,
    icon: "cookie"
  },
  {
    id: "whole-eggs",
    name: "Whole Eggs (Grade A)",
    subtext: "Poached / soft boiled · 143 kcal",
    category: "vegetarian",
    categoryLabel: "VEGETARIAN",
    proteinPer100g: 12.6,
    caloriesPer100g: 143,
    carbsPer100g: 0.8,
    fatPer100g: 9.5,
    commonServing: "2 large ≈ 100g",
    servingWeightG: 100,
    proteinPerServe: 12.6,
    caloriesPerServe: 143,
    carbsPerServe: 0.8,
    fatPerServe: 9.5,
    leucinePerServe: 1.12,
    diaasScore: 1.13,
    icon: "egg"
  },
  {
    id: "firm-tofu",
    name: "Firm Organic Tofu",
    subtext: "Pressed, soy bean curd · 124 kcal",
    category: "plant-based",
    categoryLabel: "PLANT-BASED",
    proteinPer100g: 15.8,
    caloriesPer100g: 124,
    carbsPer100g: 2.8,
    fatPer100g: 6.5,
    commonServing: "1/2 block ≈ 126g",
    servingWeightG: 126,
    proteinPerServe: 19.9,
    caloriesPerServe: 156,
    carbsPerServe: 3.5,
    fatPerServe: 8.2,
    leucinePerServe: 1.25,
    diaasScore: 0.98,
    icon: "layers"
  },
  {
    id: "fresh-paneer",
    name: "Fresh Paneer (Indian Cheese)",
    subtext: "Low moisture, unripened · 265 kcal",
    category: "dairy",
    categoryLabel: "DAIRY",
    proteinPer100g: 18.3,
    caloriesPer100g: 265,
    carbsPer100g: 3.4,
    fatPer100g: 20.8,
    commonServing: "100g cubed ≈ 100g",
    servingWeightG: 100,
    proteinPerServe: 18.3,
    caloriesPerServe: 265,
    carbsPerServe: 3.4,
    fatPerServe: 20.8,
    leucinePerServe: 1.62,
    diaasScore: 1.12,
    icon: "box"
  },
  {
    id: "red-lentils",
    name: "Red Lentils (Cooked)",
    subtext: "Split red dal, boiled · 116 kcal",
    category: "legumes",
    categoryLabel: "LEGUMES",
    proteinPer100g: 9.0,
    caloriesPer100g: 116,
    carbsPer100g: 20.1,
    fatPer100g: 0.4,
    commonServing: "1 cup cooked ≈ 198g",
    servingWeightG: 198,
    proteinPerServe: 17.8,
    caloriesPerServe: 230,
    carbsPerServe: 39.8,
    fatPerServe: 0.8,
    leucinePerServe: 0.78,
    diaasScore: 0.62,
    icon: "circle-dot"
  },
  {
    id: "edamame",
    name: "Edamame (Steamed)",
    subtext: "Young green soybeans · 121 kcal",
    category: "legumes",
    categoryLabel: "LEGUMES",
    proteinPer100g: 11.9,
    caloriesPer100g: 121,
    carbsPer100g: 8.9,
    fatPer100g: 5.2,
    commonServing: "1 cup shelled ≈ 155g",
    servingWeightG: 155,
    proteinPerServe: 18.4,
    caloriesPerServe: 188,
    carbsPerServe: 13.8,
    fatPerServe: 8.1,
    leucinePerServe: 1.05,
    diaasScore: 0.95,
    icon: "sprout"
  },
  {
    id: "raw-almonds",
    name: "Raw Whole Almonds",
    subtext: "California unblanched · 579 kcal",
    category: "nuts",
    categoryLabel: "NUTS & SEEDS",
    proteinPer100g: 21.2,
    caloriesPer100g: 579,
    carbsPer100g: 21.6,
    fatPer100g: 49.9,
    commonServing: "1 handful ≈ 28g",
    servingWeightG: 28,
    proteinPerServe: 5.9,
    caloriesPerServe: 162,
    carbsPerServe: 6.0,
    fatPerServe: 14.0,
    leucinePerServe: 1.48,
    diaasScore: 0.45,
    icon: "shield"
  },
  {
    id: "lean-beef",
    name: "Lean Ground Beef (95/5)",
    subtext: "Pan-browned crumbles · 171 kcal",
    category: "poultry",
    categoryLabel: "POULTRY & MEAT",
    proteinPer100g: 26.1,
    caloriesPer100g: 171,
    carbsPer100g: 0,
    fatPer100g: 6.8,
    commonServing: "1 patty ≈ 150g",
    servingWeightG: 150,
    proteinPerServe: 39.2,
    caloriesPerServe: 256,
    carbsPerServe: 0,
    fatPerServe: 10.2,
    leucinePerServe: 2.25,
    diaasScore: 1.10,
    icon: "flame"
  },
  {
    id: "yellowfin-tuna",
    name: "Yellowfin Tuna (Canned in Water)",
    subtext: "Wild caught, drained · 116 kcal",
    category: "seafood",
    categoryLabel: "SEAFOOD",
    proteinPer100g: 25.5,
    caloriesPer100g: 116,
    carbsPer100g: 0,
    fatPer100g: 0.8,
    commonServing: "1 can ≈ 140g",
    servingWeightG: 140,
    proteinPerServe: 35.7,
    caloriesPerServe: 162,
    carbsPerServe: 0,
    fatPerServe: 1.1,
    leucinePerServe: 2.15,
    diaasScore: 1.07,
    icon: "fish"
  },
  {
    id: "cottage-cheese",
    name: "Low-Fat Cottage Cheese (1%)",
    subtext: "Slow-release micellar casein · 72 kcal",
    category: "dairy",
    categoryLabel: "DAIRY",
    proteinPer100g: 12.4,
    caloriesPer100g: 72,
    carbsPer100g: 2.7,
    fatPer100g: 1.0,
    commonServing: "1 cup ≈ 226g",
    servingWeightG: 226,
    proteinPerServe: 28.0,
    caloriesPerServe: 163,
    carbsPerServe: 6.1,
    fatPerServe: 2.3,
    leucinePerServe: 1.42,
    diaasScore: 1.15,
    icon: "cookie"
  },
  {
    id: "tempeh",
    name: "Organic Soy Tempeh",
    subtext: "Fermented whole grain & bean · 192 kcal",
    category: "plant-based",
    categoryLabel: "PLANT-BASED",
    proteinPer100g: 20.3,
    caloriesPer100g: 192,
    carbsPer100g: 7.6,
    fatPer100g: 10.8,
    commonServing: "1 portion ≈ 100g",
    servingWeightG: 100,
    proteinPerServe: 20.3,
    caloriesPerServe: 192,
    carbsPerServe: 7.6,
    fatPerServe: 10.8,
    leucinePerServe: 1.60,
    diaasScore: 0.96,
    icon: "layers"
  },
  {
    id: "liquid-egg-whites",
    name: "Pure Liquid Egg Whites",
    subtext: "Pasteurized cage-free · 48 kcal",
    category: "vegetarian",
    categoryLabel: "VEGETARIAN",
    proteinPer100g: 10.9,
    caloriesPer100g: 48,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    commonServing: "1 cup ≈ 243g",
    servingWeightG: 243,
    proteinPerServe: 26.5,
    caloriesPerServe: 117,
    carbsPerServe: 1.7,
    fatPerServe: 0.5,
    leucinePerServe: 1.25,
    diaasScore: 1.18,
    icon: "egg"
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { FOODS_DATA };
}
